use_frameworks!

platform :ios, '8.0'

target 'HBGifView_Example' do
  pod 'HBGifView', :path => '../'

  target 'HBGifView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
